app/models.py
from . import db 
from . import db,create_app
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from . import login_manager

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User (db.Model,UserMixin):
    __tablename__='users'
    id=db.Column(db.Integer, primary_key=True)
    username=db.Column(db.String(255))
    email=db.Column(db.String(255))
    pass_secure=db.Column(db.String(255))
    profilepicpath=db.Column(db.String(255))
    comments=db.relationship('Comment',backref='user',lazy='dynamic')
    blogs=db.relationship('Blog',backref='user',lazy=True)

    @property
    def password(self):
        raise AttributeError('you cannot read the password Attribute')

    @password.setter
    def password(self,password):
        self.pass_secure=generate_password_hash(password)

    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)        




    def __repr__(self):
        return f'User {self.username}'


class Comment(db.Model):
    __tablename__='comments'
    id=db.Column(db.Integer,primary_key=True)
    comment=db.Column(db.String(255))
    user_id=db.Column(db.Integer,db.ForeignKey('users.id'))
    blog_id=db.Column(db.Integer,db.ForeignKey('blogs.id'))
    name=db.Column(db.String(255))

    def __repr__(self):
        return f'User {self.comment}'  


class Blog(db.Model):
    __tablename__='blogs'
    id=db.Column(db.Integer,primary_key=True)
    title=db.Column(db.String(255))
    blog=db.Column(db.String(10000000))
    user_id=db.Column(db.Integer,db.ForeignKey('users.id'))
    name=db.Column(db.String(255))
    comment=db.relationship('Comment',backref='blogs',lazy='dynamic')

class Quote:
    def __init__(self,author,id,quote,):
        self.id=id
        self.quote=quote
        self.author=author

   

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,PasswordField,SubmitField,BooleanField,SelectField
from wtforms.fields.simple import TextAreaField
from wtforms.validators import Required,Email,EqualTo, ValidationError


class UpdateProfile(FlaskForm):
    bio=TextAreaField('Bio',validators=[Required()])
    submit=SubmitField('Submit')

class submitblogform(FlaskForm):
    title=StringField('Title of your blog',validators=[Required()])
    blog=TextAreaField('Your blog')
    

    submit=SubmitField('Submit')

class submitcommentform(FlaskForm):
    
    comment=TextAreaField('Your comment',validators=[Required()])
    
    submit=SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from config import  config_options
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_simplemde import SimpleMDE


bootstrap=Bootstrap()
db=SQLAlchemy()
login_manager=LoginManager()
login_manager.session_protection='strong'
login_manager.login_view='auth.login'
simple=SimpleMDE()

photos=UploadSet('photos',IMAGES)


def create_app(config_name):
    app= Flask(__name__)

    #creating app configurations
    app.config.from_object(config_options[config_name])

    #initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    simple.init_app(app)

    configure_uploads(app,photos)


   

    #register Blueprint
    from .main import main as main_Blueprint
    app.register_blueprint(main_Blueprint)

    from .auth import auth as auth_Blueprint
    app.register_blueprint(auth_Blueprint,url_prefix='/authenticate')

    


    return app

app/main/__init__.py
from flask import Blueprint
main =Blueprint('main',__name__)
from . import views,errors

app/main/views.py
from app.request import get_quote
from flask.helpers import flash
from app.main.forms import submitblogform, submitcommentform
from flask import render_template,request,redirect,url_for
from . import main
from app.models import Blog, Comment, User 
from flask_login import login_user,login_required,logout_user,current_user
from .. import db, photos
import markdown2 

@main.route('/')
def index():
    return render_template('index.html')

@main.route('/user/<uname>')
def profile(uname):
    user=User.query.filter_by(username=uname).first()
    user_idd=user.id

    if user is None:
        abort(404)

    return render_template('profile/profile.html',user=user)        


@main.route('/user/<uname>/update/pic' , methods=['POST','GET'])
@login_required
def update_pic(uname):
    user=User.query.filter_by(username=uname).first()
    if 'photo' in request.files:
        filename=photos.save(request.files['photo'])

        path=f'photos/{filename}'
        user.profilepicpath=path

        db.session.commit()
        return redirect(url_for('main.profile',uname=uname))    

@main.route('/submitblog',methods=['GET','POST'])
@login_required
def submitblog():
    form=submitblogform(request.form)

    id=current_user.id
    
    
    if request.method =='POST' and form.validate_on_submit():
        blog=Blog(title=form.title.data,blog=form.blog.data,user_id=id,name=current_user.username)
        db.session.add(blog)
        db.session.commit()

        
        
        #return redirect(url_for('main.profile',uname=uname))
        
        return redirect(url_for('.blogs'))
                
    return render_template('blog/submitblog.html',form=form,name=current_user.username,user_id=id)


@main.route('/blogs')
def blogs():
    Allblogs=Blog.query.filter().all()

    return render_template('blogs.html',Allblogs=Allblogs)

@main.route('/user/<blogid>/comments',methods=['GET','POST'])
@login_required
def comment(blogid):
    blog=Blog.query.filter_by(id=blogid).first()
    form=submitcommentform()
    if request.method =='POST' and form.validate_on_submit():
        comment=Comment(comment=form.comment.data,user_id=current_user.id,name=current_user.username,blog_id=blogid)
        db.session.add(comment)
        db.session.commit()

        blogid=blogid
        

        return redirect (url_for('main.singleblog',blogid=blogid))

    return render_template('blog/comments.html',form=form,blogid=blogid)

@main.route('/blog/<blogid>')
def singleblog(blogid):
    comments=Comment.query.filter_by(blog_id=blogid).all()
    blog=Blog.query.filter_by(id=blogid).first()
   
    format_blog = markdown2.markdown(blog.blog,extras=["code-friendly", "fenced-code-blocks"])
    quote=get_quote()
    
    return render_template('blog/singleblog.html',blog=blog,comments=comments,format_blog=format_blog,quote=quote)


@main.route('/delete/<blogid>',methods=['POST'])  
@login_required
def deleteblog(blogid):
    blog=Blog.query.filter_by(id=blogid).first()
    db.session.delete(blog)
    db.session.commit()
    flash('blog deleted')
    return redirect(url_for('main.blogs'))

@main.route('/delete comment/<blogid>/<commentid>',methods=['POST'])  
@login_required
def deletecomment(commentid,blogid):
    comment=Comment.query.filter_by(id=commentid).first()
    blog=Blog.query.filter_by(id=blogid).first()
    blogid=blog.id
    db.session.delete(comment)
    db.session.commit()
    flash('comment deleted')
    return redirect(url_for('main.singleblog',blogid=blogid))    

app/templates/base.html
<html>

<head>
{%block styles%}

  <!--Importing the simple mde css and js files  -->
  {{ simplemde.css}}
  {{ simplemde.js }}

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <link href="\static\css\index.css" rel="stylesheet">
    
  
{%endblock%}
</head>

<body>

{%block navbar%}
    <nav class="navbar navbar-expand-lg navbar-light bg-light navbarclass py-2">
        <div id="navid" class="container-fluid navbarclass" >
            <img src="/static/images/blogging.svg" alt="" width="30" height="24">

            <a class="navbar-brand" href="/">BLOG</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/">Home</a>
                    </li>
                     <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{{ url_for('main.blogs')}}">Blogs</a>
                    </li>
                    
                    </ul>
        
                    <ul class="nav navbar-nav navbar-right">
                   
       
                    
                    {% if current_user.is_authenticated%}
                     <li>
                    <a class="btn btn-primary " href="{{ url_for('main.submitblog')}}" role="button">Submit blog</a>

                    </li>
                     <li class="nav-item">
                        <a class="nav-link" href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a>
                    </li>
    
                    
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('auth.logout')}}">Signout</a>
                    </li>
                    
                    {%else%}
                        <li class="nav-item">
                        <a class="nav-link" href="{{url_for('auth.login')}}">login</a>
                    </li>
                    {%endif%} 
                    
                     </ul>
                

            </div>
        </div>
    </nav>
    {%endblock%}
    {% block content %}
    {% endblock%}



   
</body>

</html>

app/templates/blog/comments.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}
{%block content%}
<div class="container">
<h1>comment below</h2>
{% if current_user.is_authenticated %}
 
{% endif %}
{{ wtf.quick_form(form) }}
</div>
{%endblock%}

app/templates/blog/singleblog.html
{% extends 'base.html'%}
{%block styles%}

<link href="\static\css\index.css" rel="stylesheet">
{{super()}}
    
{%endblock%}
{% block content%}
<div class="container">
    <div class="row">
            <div class="col-md-8">
                <h1 class="display-4">{{blog.title}}</h1>
                {{format_blog|safe}}

                <h6>Submitted by : {{blog.name}}</h6>
                
                <p class="lead">
                <a class="btn btn-primary btn-sm" href="{{url_for('main.comment',blogid=blog.id)}}" role="button">Comment on blog</a>
                </p>
            
            
                <hr class="my-4">
                {% for message in get_flashed_messages() %}
                    <div class="alert alert-danger">
                        <button type="button" class="close" data-dismiss="alert">&times;</button> {{ message }}
                    </div>
                    {% endfor %}
                <h4>Comments: </h4>
                    <div class="row">
        
                    {%for comment in comments%}
                    <div class="col-md-3 comment">
                        
                        <p>{{comment.comment}}</p>
                        <p>Comment by: ~{{comment.name}}
                        
                    </div>
                    <form action="{{ url_for('main.deletecomment',commentid=comment.id,blogid=blog.id) }}" method='post' class="delete-entryy">
                <input type="hidden" name="comment_id" value="{{ comment.id }}">
                <input class="btn btn-danger btn-sm" type="submit" value="Delete Comment" />
                </form>
                    {%endfor%}
                    </div>
               

                     
            </div>
            
            <div class="col-md-4" id="Quote">
            <center>
            <h1 class="titlee">Quote</h1>
            <p>Todays quotes is:</p>
            <p>{{quote.quote}}</p>
            <p>By {{quote.author}}</p>

             </center>
            </div>
           
    </div>


        {%endblock%}
</div>

app/templates/blog/submitblog.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}
{%block styles%}
{{super()}}
{%endblock%}
{%block content%}
<div class="container">
<div class="col-md-4">
<h6>Hello {{name}}</h6>
<h6>Submit Your blog below</h6>

            {{ wtf.quick_form(form) }}
             {{simplemde.load}}
            
            
        </div>
        </div>
        
{%endblock%}

app/templates/blogs.html
{% extends 'base.html'%}
{% block content%}


<div class="container">
{% for message in get_flashed_messages() %}
            <div class="alert alert-danger">
                <button type="button" class="close" data-dismiss="alert">&times;</button> {{ message }}
            </div>
            {% endfor %}

{%if Allblogs%}
{% for blog in Allblogs%}

<div class="jumbotron jumbos">

  <h1 class="display-4 title">{{blog.title}}</h1>
  <p class="lead  text-truncate">{{blog.blog}}</p>
  <hr class="my-4">
  <p>submitted by: {{blog.name}}</p>
 
  <p class="lead">
    <a class="btn btn-primary btn-sm" href="{{url_for('main.comment',blogid=blog.id)}}" role="button">Comment on blog</a>
  </p>
   <p class="lead ">
    <a class="btn btn-info btn-sm" href="{{url_for('main.singleblog',blogid=blog.id)}}" role="button">view more</a>
  </p>
 
  <form action="{{ url_for('main.deleteblog',blogid=blog.id) }}" method='post' class="delete-entry">
          <input type="hidden" name="blog_id" value="{{ blog.id }}">
          <input class="btn btn-danger btn-sm" type="submit" value="Delete Blog" />
</form>
</div>


<br></br>

{%endfor%}

{%else%}
<p>No blogs available in this category</p>
{%endif%}
{%endblock%}
</div>

app/templates/error.html
<!--styles block-->
<html>

<head>

    <link rel="stylesheet" href="{{url_for('static',filename='css/error.css')}}">
</head>

<body>

    {% block content %}
    <div class="notfound">
        <div class="centered"><span class="inverted">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>&nbsp;</div>
        <div class="centered"><span class="inverted">&nbsp;4&nbsp;0&nbsp;4&nbsp;</span><span class="shadow">&nbsp;</span></div>
        <div class="centered"><span class="inverted">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span class="shadow">&nbsp;</span></div>
        <div class="centered">&nbsp;<span class="shadow">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></div>
        <div class="row">&nbsp;</div>
        <div class="row">A fatal exception 404 has occurred at C0DE:ABAD1DEA in 0xC0DEBA5E.</div>
        <div class="row">The current request will be terminated.</div>
        <div class="row">&nbsp;</div>
        <div class="row">* Press any key to return to the previous page.</div>
        <div class="row">* Press CTRL+ALT+DEL to restart your computer. You will</div>
        <div class="row">&nbsp;&nbsp;lose any unsaved information in all applications.</div>
        <div class="row">&nbsp;</div>
        <div class="centered">Press any key to continue...<span class="blink">&#9608;</span></div>
    </div>
    {% endblock %}
</body>

</html>

app/templates/index.html
{% extends 'base.html'%} {%block styles%} {{super()}}
<link href="\static\css\index.css" rel="stylesheet"> {%endblock%} {%block content%}
<div class="container">
    <div class="row mt-3 words">
        <div class="col-md-6">
            <img src="/static/images/welcome.png" alt="welcome" style="width:448px;height:448px;">
        </div>
        <div class="col-md-6 mt-3 pt-2">
         <center>
            <h1 class="titlee">
                <center>BLOG</center>
            </h1>
            <br></br>
            <h5>Blogging can be incredibly valuable to a variety of people and for a variety of reasons. Blogging is not just for businesses! I’ve benefited personally, professionally, and financially from blogging. </h5>
            <br></br>

            <h5> Writing has actually become one of my favorite hobbies. I recommend blogging to almost everyone I meet.</h5>

            <h5>Read the blogs below </h5>
           
            <a class="btn btn-primary " href="{{ url_for('main.blogs')}}" role="button">View Blogs</a>

</center>
    
           
        </div>
    </div>
</div>

 {%endblock%}

app/templates/profile/profile.html
{% extends 'base.html'%}
{%block styles%}
{{super()}}
{%endblock%}
{%block content%}
<div class="container">
    <div class="row ">
        <div class="col-md-4 my-4 4 pb-4 ">
        <h2 class="pb-4">Your details</h2>
        {%if user.profilepicpath%}
        <img src="{{url_for('static',filename=user.profilepicpath)}}" alt="" class="img_thumbnail" style="width:300px;height:400px;>
        {%else %}
        <p>No profile pic</p>
        {%endif%}
        {%if user== current_user%}
        <form action ="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype="multipart/form-data">
        <input type="file"  name="photo" class="form-control" required>
        <input type="submit">


        {%endif%}
            <h6>Username:</h6>
            <p>{{user.username}}</p>
            <h6>Email:</h6>
            <p>{{user.email}}</p>
            <h6>Bio:</h6>
            {%if user.bio%}
            <p>{{user.bio}}</p>
            {%else%}
            <P>{{user.username}} has no bio</p>
            {%endif%}
            {% if user == current_user %}
{% endif %}


        </div>
        <div class="col-md-8 my-4 pb-4 pr-5">
        <h2 class="pb-4" ><center>Your Blogs</center></h2>
        {%if pitches:%}
        {%for pitch in pitches%}
        <div class="jumbotron jumbos">
  <h1 class="display-4">{{pitch.title}}</h1>
  <p class="lead">{{pitch.pitch}}</p>
  <hr class="my-4">
  <p>{{pitch.category}}</p>
  <p class="lead">
    <a class="btn btn-primary btn-lg" href="{{url_for('main.comment',category=pitch.category,pitchid=pitch.id)}}" role="button">Comment on pitch</a>
                                            

  </p>
</div>
    
        {%endfor%}


        {%else%}
        <br></br>
        <h6>you have no blogs on the App</h6>
        {%endif%}
        </div>
    </div>
</div>

{% endblock %}